
services:
  # Backend (NestJS) - Production
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.prod
    container_name: hukbaek-backend
    env_file:
      - .env.local
    ports:
      - "4000:4000"
    restart: unless-stopped
    mem_limit: 600m
    mem_reservation: 450m
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512

  # Frontend (Svelte + Nginx) - Production
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.prod
    container_name: hukbaek-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    mem_limit: 150m
    mem_reservation: 100m
