
services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: hukbaek-db
    environment:
      POSTGRES_DB: black_and_white
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d black_and_white"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (NestJS)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    container_name: hukbaek-backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      DATABASE_NAME: black_and_white
      NODE_ENV: development
      PORT: 4000
      FRONTEND_URL: http://localhost:5173
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/apps/backend/node_modules
      - /app/packages/shared/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "cd /app/packages/shared && pnpm build && cd /app/apps/backend && pnpm dev"

  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    container_name: hukbaek-frontend
    environment:
      VITE_API_BASE: http://localhost:4000/api
      VITE_WS_URL: http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/packages/shared/node_modules
    depends_on:
      - backend
    command: sh -c "cd /app/apps/frontend && pnpm dev --host"

volumes:
  postgres_data:
