services:
  # Backend (NestJS) - Production
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: hukbaek-backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: unless-stopped
    mem_limit: 900m
    mem_reservation: 750m
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=800
